/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JugadorRouteImport } from './routes/jugador'
import { Route as FisioRouteImport } from './routes/fisio'
import { Route as EntrenadorRouteImport } from './routes/entrenador'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JugadorIndexRouteImport } from './routes/jugador.index'
import { Route as FisioIndexRouteImport } from './routes/fisio.index'
import { Route as EntrenadorIndexRouteImport } from './routes/entrenador.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as JugadorPerfilRouteImport } from './routes/jugador.perfil'
import { Route as JugadorMensajesRouteImport } from './routes/jugador.mensajes'
import { Route as JugadorLesionRouteImport } from './routes/jugador.lesion'
import { Route as JugadorHistorialRouteImport } from './routes/jugador.historial'
import { Route as JugadorDocumentosRouteImport } from './routes/jugador.documentos'
import { Route as JugadorCitasRouteImport } from './routes/jugador.citas'
import { Route as FisioPerfilRouteImport } from './routes/fisio.perfil'
import { Route as FisioMensajesRouteImport } from './routes/fisio.mensajes'
import { Route as FisioLesionesRouteImport } from './routes/fisio.lesiones'
import { Route as FisioJugadoresRouteImport } from './routes/fisio.jugadores'
import { Route as FisioHistoricoRouteImport } from './routes/fisio.historico'
import { Route as FisioFacturacionRouteImport } from './routes/fisio.facturacion'
import { Route as FisioDocumentosRouteImport } from './routes/fisio.documentos'
import { Route as FisioAgendaRouteImport } from './routes/fisio.agenda'
import { Route as EntrenadorMensajesRouteImport } from './routes/entrenador.mensajes'
import { Route as EntrenadorHistoricoRouteImport } from './routes/entrenador.historico'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as AdminMensajesRouteImport } from './routes/admin.mensajes'
import { Route as AdminHistoricoRouteImport } from './routes/admin.historico'
import { Route as AdminFacturasRouteImport } from './routes/admin.facturas'
import { Route as AdminCitasRouteImport } from './routes/admin.citas'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JugadorRoute = JugadorRouteImport.update({
  id: '/jugador',
  path: '/jugador',
  getParentRoute: () => rootRouteImport,
} as any)
const FisioRoute = FisioRouteImport.update({
  id: '/fisio',
  path: '/fisio',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrenadorRoute = EntrenadorRouteImport.update({
  id: '/entrenador',
  path: '/entrenador',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JugadorIndexRoute = JugadorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JugadorRoute,
} as any)
const FisioIndexRoute = FisioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FisioRoute,
} as any)
const EntrenadorIndexRoute = EntrenadorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EntrenadorRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const JugadorPerfilRoute = JugadorPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => JugadorRoute,
} as any)
const JugadorMensajesRoute = JugadorMensajesRouteImport.update({
  id: '/mensajes',
  path: '/mensajes',
  getParentRoute: () => JugadorRoute,
} as any)
const JugadorLesionRoute = JugadorLesionRouteImport.update({
  id: '/lesion',
  path: '/lesion',
  getParentRoute: () => JugadorRoute,
} as any)
const JugadorHistorialRoute = JugadorHistorialRouteImport.update({
  id: '/historial',
  path: '/historial',
  getParentRoute: () => JugadorRoute,
} as any)
const JugadorDocumentosRoute = JugadorDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => JugadorRoute,
} as any)
const JugadorCitasRoute = JugadorCitasRouteImport.update({
  id: '/citas',
  path: '/citas',
  getParentRoute: () => JugadorRoute,
} as any)
const FisioPerfilRoute = FisioPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => FisioRoute,
} as any)
const FisioMensajesRoute = FisioMensajesRouteImport.update({
  id: '/mensajes',
  path: '/mensajes',
  getParentRoute: () => FisioRoute,
} as any)
const FisioLesionesRoute = FisioLesionesRouteImport.update({
  id: '/lesiones',
  path: '/lesiones',
  getParentRoute: () => FisioRoute,
} as any)
const FisioJugadoresRoute = FisioJugadoresRouteImport.update({
  id: '/jugadores',
  path: '/jugadores',
  getParentRoute: () => FisioRoute,
} as any)
const FisioHistoricoRoute = FisioHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => FisioRoute,
} as any)
const FisioFacturacionRoute = FisioFacturacionRouteImport.update({
  id: '/facturacion',
  path: '/facturacion',
  getParentRoute: () => FisioRoute,
} as any)
const FisioDocumentosRoute = FisioDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => FisioRoute,
} as any)
const FisioAgendaRoute = FisioAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => FisioRoute,
} as any)
const EntrenadorMensajesRoute = EntrenadorMensajesRouteImport.update({
  id: '/mensajes',
  path: '/mensajes',
  getParentRoute: () => EntrenadorRoute,
} as any)
const EntrenadorHistoricoRoute = EntrenadorHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => EntrenadorRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMensajesRoute = AdminMensajesRouteImport.update({
  id: '/mensajes',
  path: '/mensajes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHistoricoRoute = AdminHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFacturasRoute = AdminFacturasRouteImport.update({
  id: '/facturas',
  path: '/facturas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCitasRoute = AdminCitasRouteImport.update({
  id: '/citas',
  path: '/citas',
  getParentRoute: () => AdminRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/entrenador': typeof EntrenadorRouteWithChildren
  '/fisio': typeof FisioRouteWithChildren
  '/jugador': typeof JugadorRouteWithChildren
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/registro': typeof RegistroRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/citas': typeof AdminCitasRoute
  '/admin/facturas': typeof AdminFacturasRoute
  '/admin/historico': typeof AdminHistoricoRoute
  '/admin/mensajes': typeof AdminMensajesRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/entrenador/historico': typeof EntrenadorHistoricoRoute
  '/entrenador/mensajes': typeof EntrenadorMensajesRoute
  '/fisio/agenda': typeof FisioAgendaRoute
  '/fisio/documentos': typeof FisioDocumentosRoute
  '/fisio/facturacion': typeof FisioFacturacionRoute
  '/fisio/historico': typeof FisioHistoricoRoute
  '/fisio/jugadores': typeof FisioJugadoresRoute
  '/fisio/lesiones': typeof FisioLesionesRoute
  '/fisio/mensajes': typeof FisioMensajesRoute
  '/fisio/perfil': typeof FisioPerfilRoute
  '/jugador/citas': typeof JugadorCitasRoute
  '/jugador/documentos': typeof JugadorDocumentosRoute
  '/jugador/historial': typeof JugadorHistorialRoute
  '/jugador/lesion': typeof JugadorLesionRoute
  '/jugador/mensajes': typeof JugadorMensajesRoute
  '/jugador/perfil': typeof JugadorPerfilRoute
  '/admin/': typeof AdminIndexRoute
  '/entrenador/': typeof EntrenadorIndexRoute
  '/fisio/': typeof FisioIndexRoute
  '/jugador/': typeof JugadorIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/registro': typeof RegistroRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/citas': typeof AdminCitasRoute
  '/admin/facturas': typeof AdminFacturasRoute
  '/admin/historico': typeof AdminHistoricoRoute
  '/admin/mensajes': typeof AdminMensajesRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/entrenador/historico': typeof EntrenadorHistoricoRoute
  '/entrenador/mensajes': typeof EntrenadorMensajesRoute
  '/fisio/agenda': typeof FisioAgendaRoute
  '/fisio/documentos': typeof FisioDocumentosRoute
  '/fisio/facturacion': typeof FisioFacturacionRoute
  '/fisio/historico': typeof FisioHistoricoRoute
  '/fisio/jugadores': typeof FisioJugadoresRoute
  '/fisio/lesiones': typeof FisioLesionesRoute
  '/fisio/mensajes': typeof FisioMensajesRoute
  '/fisio/perfil': typeof FisioPerfilRoute
  '/jugador/citas': typeof JugadorCitasRoute
  '/jugador/documentos': typeof JugadorDocumentosRoute
  '/jugador/historial': typeof JugadorHistorialRoute
  '/jugador/lesion': typeof JugadorLesionRoute
  '/jugador/mensajes': typeof JugadorMensajesRoute
  '/jugador/perfil': typeof JugadorPerfilRoute
  '/admin': typeof AdminIndexRoute
  '/entrenador': typeof EntrenadorIndexRoute
  '/fisio': typeof FisioIndexRoute
  '/jugador': typeof JugadorIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/entrenador': typeof EntrenadorRouteWithChildren
  '/fisio': typeof FisioRouteWithChildren
  '/jugador': typeof JugadorRouteWithChildren
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/registro': typeof RegistroRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/citas': typeof AdminCitasRoute
  '/admin/facturas': typeof AdminFacturasRoute
  '/admin/historico': typeof AdminHistoricoRoute
  '/admin/mensajes': typeof AdminMensajesRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/entrenador/historico': typeof EntrenadorHistoricoRoute
  '/entrenador/mensajes': typeof EntrenadorMensajesRoute
  '/fisio/agenda': typeof FisioAgendaRoute
  '/fisio/documentos': typeof FisioDocumentosRoute
  '/fisio/facturacion': typeof FisioFacturacionRoute
  '/fisio/historico': typeof FisioHistoricoRoute
  '/fisio/jugadores': typeof FisioJugadoresRoute
  '/fisio/lesiones': typeof FisioLesionesRoute
  '/fisio/mensajes': typeof FisioMensajesRoute
  '/fisio/perfil': typeof FisioPerfilRoute
  '/jugador/citas': typeof JugadorCitasRoute
  '/jugador/documentos': typeof JugadorDocumentosRoute
  '/jugador/historial': typeof JugadorHistorialRoute
  '/jugador/lesion': typeof JugadorLesionRoute
  '/jugador/mensajes': typeof JugadorMensajesRoute
  '/jugador/perfil': typeof JugadorPerfilRoute
  '/admin/': typeof AdminIndexRoute
  '/entrenador/': typeof EntrenadorIndexRoute
  '/fisio/': typeof FisioIndexRoute
  '/jugador/': typeof JugadorIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/entrenador'
    | '/fisio'
    | '/jugador'
    | '/login'
    | '/mcp'
    | '/registro'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/citas'
    | '/admin/facturas'
    | '/admin/historico'
    | '/admin/mensajes'
    | '/admin/usuarios'
    | '/entrenador/historico'
    | '/entrenador/mensajes'
    | '/fisio/agenda'
    | '/fisio/documentos'
    | '/fisio/facturacion'
    | '/fisio/historico'
    | '/fisio/jugadores'
    | '/fisio/lesiones'
    | '/fisio/mensajes'
    | '/fisio/perfil'
    | '/jugador/citas'
    | '/jugador/documentos'
    | '/jugador/historial'
    | '/jugador/lesion'
    | '/jugador/mensajes'
    | '/jugador/perfil'
    | '/admin/'
    | '/entrenador/'
    | '/fisio/'
    | '/jugador/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/mcp'
    | '/registro'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/citas'
    | '/admin/facturas'
    | '/admin/historico'
    | '/admin/mensajes'
    | '/admin/usuarios'
    | '/entrenador/historico'
    | '/entrenador/mensajes'
    | '/fisio/agenda'
    | '/fisio/documentos'
    | '/fisio/facturacion'
    | '/fisio/historico'
    | '/fisio/jugadores'
    | '/fisio/lesiones'
    | '/fisio/mensajes'
    | '/fisio/perfil'
    | '/jugador/citas'
    | '/jugador/documentos'
    | '/jugador/historial'
    | '/jugador/lesion'
    | '/jugador/mensajes'
    | '/jugador/perfil'
    | '/admin'
    | '/entrenador'
    | '/fisio'
    | '/jugador'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/entrenador'
    | '/fisio'
    | '/jugador'
    | '/login'
    | '/mcp'
    | '/registro'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/citas'
    | '/admin/facturas'
    | '/admin/historico'
    | '/admin/mensajes'
    | '/admin/usuarios'
    | '/entrenador/historico'
    | '/entrenador/mensajes'
    | '/fisio/agenda'
    | '/fisio/documentos'
    | '/fisio/facturacion'
    | '/fisio/historico'
    | '/fisio/jugadores'
    | '/fisio/lesiones'
    | '/fisio/mensajes'
    | '/fisio/perfil'
    | '/jugador/citas'
    | '/jugador/documentos'
    | '/jugador/historial'
    | '/jugador/lesion'
    | '/jugador/mensajes'
    | '/jugador/perfil'
    | '/admin/'
    | '/entrenador/'
    | '/fisio/'
    | '/jugador/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  EntrenadorRoute: typeof EntrenadorRouteWithChildren
  FisioRoute: typeof FisioRouteWithChildren
  JugadorRoute: typeof JugadorRouteWithChildren
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  RegistroRoute: typeof RegistroRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jugador': {
      id: '/jugador'
      path: '/jugador'
      fullPath: '/jugador'
      preLoaderRoute: typeof JugadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fisio': {
      id: '/fisio'
      path: '/fisio'
      fullPath: '/fisio'
      preLoaderRoute: typeof FisioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrenador': {
      id: '/entrenador'
      path: '/entrenador'
      fullPath: '/entrenador'
      preLoaderRoute: typeof EntrenadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jugador/': {
      id: '/jugador/'
      path: '/'
      fullPath: '/jugador/'
      preLoaderRoute: typeof JugadorIndexRouteImport
      parentRoute: typeof JugadorRoute
    }
    '/fisio/': {
      id: '/fisio/'
      path: '/'
      fullPath: '/fisio/'
      preLoaderRoute: typeof FisioIndexRouteImport
      parentRoute: typeof FisioRoute
    }
    '/entrenador/': {
      id: '/entrenador/'
      path: '/'
      fullPath: '/entrenador/'
      preLoaderRoute: typeof EntrenadorIndexRouteImport
      parentRoute: typeof EntrenadorRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/jugador/perfil': {
      id: '/jugador/perfil'
      path: '/perfil'
      fullPath: '/jugador/perfil'
      preLoaderRoute: typeof JugadorPerfilRouteImport
      parentRoute: typeof JugadorRoute
    }
    '/jugador/mensajes': {
      id: '/jugador/mensajes'
      path: '/mensajes'
      fullPath: '/jugador/mensajes'
      preLoaderRoute: typeof JugadorMensajesRouteImport
      parentRoute: typeof JugadorRoute
    }
    '/jugador/lesion': {
      id: '/jugador/lesion'
      path: '/lesion'
      fullPath: '/jugador/lesion'
      preLoaderRoute: typeof JugadorLesionRouteImport
      parentRoute: typeof JugadorRoute
    }
    '/jugador/historial': {
      id: '/jugador/historial'
      path: '/historial'
      fullPath: '/jugador/historial'
      preLoaderRoute: typeof JugadorHistorialRouteImport
      parentRoute: typeof JugadorRoute
    }
    '/jugador/documentos': {
      id: '/jugador/documentos'
      path: '/documentos'
      fullPath: '/jugador/documentos'
      preLoaderRoute: typeof JugadorDocumentosRouteImport
      parentRoute: typeof JugadorRoute
    }
    '/jugador/citas': {
      id: '/jugador/citas'
      path: '/citas'
      fullPath: '/jugador/citas'
      preLoaderRoute: typeof JugadorCitasRouteImport
      parentRoute: typeof JugadorRoute
    }
    '/fisio/perfil': {
      id: '/fisio/perfil'
      path: '/perfil'
      fullPath: '/fisio/perfil'
      preLoaderRoute: typeof FisioPerfilRouteImport
      parentRoute: typeof FisioRoute
    }
    '/fisio/mensajes': {
      id: '/fisio/mensajes'
      path: '/mensajes'
      fullPath: '/fisio/mensajes'
      preLoaderRoute: typeof FisioMensajesRouteImport
      parentRoute: typeof FisioRoute
    }
    '/fisio/lesiones': {
      id: '/fisio/lesiones'
      path: '/lesiones'
      fullPath: '/fisio/lesiones'
      preLoaderRoute: typeof FisioLesionesRouteImport
      parentRoute: typeof FisioRoute
    }
    '/fisio/jugadores': {
      id: '/fisio/jugadores'
      path: '/jugadores'
      fullPath: '/fisio/jugadores'
      preLoaderRoute: typeof FisioJugadoresRouteImport
      parentRoute: typeof FisioRoute
    }
    '/fisio/historico': {
      id: '/fisio/historico'
      path: '/historico'
      fullPath: '/fisio/historico'
      preLoaderRoute: typeof FisioHistoricoRouteImport
      parentRoute: typeof FisioRoute
    }
    '/fisio/facturacion': {
      id: '/fisio/facturacion'
      path: '/facturacion'
      fullPath: '/fisio/facturacion'
      preLoaderRoute: typeof FisioFacturacionRouteImport
      parentRoute: typeof FisioRoute
    }
    '/fisio/documentos': {
      id: '/fisio/documentos'
      path: '/documentos'
      fullPath: '/fisio/documentos'
      preLoaderRoute: typeof FisioDocumentosRouteImport
      parentRoute: typeof FisioRoute
    }
    '/fisio/agenda': {
      id: '/fisio/agenda'
      path: '/agenda'
      fullPath: '/fisio/agenda'
      preLoaderRoute: typeof FisioAgendaRouteImport
      parentRoute: typeof FisioRoute
    }
    '/entrenador/mensajes': {
      id: '/entrenador/mensajes'
      path: '/mensajes'
      fullPath: '/entrenador/mensajes'
      preLoaderRoute: typeof EntrenadorMensajesRouteImport
      parentRoute: typeof EntrenadorRoute
    }
    '/entrenador/historico': {
      id: '/entrenador/historico'
      path: '/historico'
      fullPath: '/entrenador/historico'
      preLoaderRoute: typeof EntrenadorHistoricoRouteImport
      parentRoute: typeof EntrenadorRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mensajes': {
      id: '/admin/mensajes'
      path: '/mensajes'
      fullPath: '/admin/mensajes'
      preLoaderRoute: typeof AdminMensajesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/historico': {
      id: '/admin/historico'
      path: '/historico'
      fullPath: '/admin/historico'
      preLoaderRoute: typeof AdminHistoricoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/facturas': {
      id: '/admin/facturas'
      path: '/facturas'
      fullPath: '/admin/facturas'
      preLoaderRoute: typeof AdminFacturasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/citas': {
      id: '/admin/citas'
      path: '/citas'
      fullPath: '/admin/citas'
      preLoaderRoute: typeof AdminCitasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminCitasRoute: typeof AdminCitasRoute
  AdminFacturasRoute: typeof AdminFacturasRoute
  AdminHistoricoRoute: typeof AdminHistoricoRoute
  AdminMensajesRoute: typeof AdminMensajesRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCitasRoute: AdminCitasRoute,
  AdminFacturasRoute: AdminFacturasRoute,
  AdminHistoricoRoute: AdminHistoricoRoute,
  AdminMensajesRoute: AdminMensajesRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface EntrenadorRouteChildren {
  EntrenadorHistoricoRoute: typeof EntrenadorHistoricoRoute
  EntrenadorMensajesRoute: typeof EntrenadorMensajesRoute
  EntrenadorIndexRoute: typeof EntrenadorIndexRoute
}

const EntrenadorRouteChildren: EntrenadorRouteChildren = {
  EntrenadorHistoricoRoute: EntrenadorHistoricoRoute,
  EntrenadorMensajesRoute: EntrenadorMensajesRoute,
  EntrenadorIndexRoute: EntrenadorIndexRoute,
}

const EntrenadorRouteWithChildren = EntrenadorRoute._addFileChildren(
  EntrenadorRouteChildren,
)

interface FisioRouteChildren {
  FisioAgendaRoute: typeof FisioAgendaRoute
  FisioDocumentosRoute: typeof FisioDocumentosRoute
  FisioFacturacionRoute: typeof FisioFacturacionRoute
  FisioHistoricoRoute: typeof FisioHistoricoRoute
  FisioJugadoresRoute: typeof FisioJugadoresRoute
  FisioLesionesRoute: typeof FisioLesionesRoute
  FisioMensajesRoute: typeof FisioMensajesRoute
  FisioPerfilRoute: typeof FisioPerfilRoute
  FisioIndexRoute: typeof FisioIndexRoute
}

const FisioRouteChildren: FisioRouteChildren = {
  FisioAgendaRoute: FisioAgendaRoute,
  FisioDocumentosRoute: FisioDocumentosRoute,
  FisioFacturacionRoute: FisioFacturacionRoute,
  FisioHistoricoRoute: FisioHistoricoRoute,
  FisioJugadoresRoute: FisioJugadoresRoute,
  FisioLesionesRoute: FisioLesionesRoute,
  FisioMensajesRoute: FisioMensajesRoute,
  FisioPerfilRoute: FisioPerfilRoute,
  FisioIndexRoute: FisioIndexRoute,
}

const FisioRouteWithChildren = FisioRoute._addFileChildren(FisioRouteChildren)

interface JugadorRouteChildren {
  JugadorCitasRoute: typeof JugadorCitasRoute
  JugadorDocumentosRoute: typeof JugadorDocumentosRoute
  JugadorHistorialRoute: typeof JugadorHistorialRoute
  JugadorLesionRoute: typeof JugadorLesionRoute
  JugadorMensajesRoute: typeof JugadorMensajesRoute
  JugadorPerfilRoute: typeof JugadorPerfilRoute
  JugadorIndexRoute: typeof JugadorIndexRoute
}

const JugadorRouteChildren: JugadorRouteChildren = {
  JugadorCitasRoute: JugadorCitasRoute,
  JugadorDocumentosRoute: JugadorDocumentosRoute,
  JugadorHistorialRoute: JugadorHistorialRoute,
  JugadorLesionRoute: JugadorLesionRoute,
  JugadorMensajesRoute: JugadorMensajesRoute,
  JugadorPerfilRoute: JugadorPerfilRoute,
  JugadorIndexRoute: JugadorIndexRoute,
}

const JugadorRouteWithChildren =
  JugadorRoute._addFileChildren(JugadorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  EntrenadorRoute: EntrenadorRouteWithChildren,
  FisioRoute: FisioRouteWithChildren,
  JugadorRoute: JugadorRouteWithChildren,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  RegistroRoute: RegistroRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
